name: Server Tests - updated

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  server-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f server/requirements.txt ]; then pip install -r server/requirements.txt; fi
        pip install pytest
        
    - name: Run tests
      working-directory: ./server
      run: |
        python -m pytest test_app.py -v